// Generated by Wrangler by running `wrangler types`

interface Env {
	CALLS_APP_ID: "3fb2121269d353478250f1dbd988735c";
	CALLS_API_TOKEN: string;
	DB_URL: string;
	Signaling: DurableObjectNamespace<import("./src/index").Signaling>;
	SessionManager: DurableObjectNamespace<import("./src/index").SessionManager>;
}
declare module "*.sql" {
	const value: string;
	export default value;
}