// Generated by Wrangler by running `wrangler types`

interface Env {
	CALLS_APP_ID: "3fb2121269d353478250f1dbd988735c";
	CALLS_API_TOKEN: string;
	EventRoom: DurableObjectNamespace<import("./src/index").EventRoom>;
	fireside_event: Hyperdrive;
}
