// Generated by Wrangler by running `wrangler types`

interface Env {
	CALLS_APP_ID: "3fb2121269d353478250f1dbd988735c";
	CALLS_API_TOKEN: string;
	DB_URL: string;
	JWT_SECRET: string;
	RoomManager: DurableObjectNamespace<import("./src/index").RoomManager>;
}
declare module "*.sql" {
	const value: string;
	export default value;
}